### ISSUE TITLE
Code availability

### ISSUE THREAD

**Issue by jcsma** [mattiasegu/darth#1]
Dear authors,

Thanks for the very interesting work at ICCV23. Could you please let us know when do you plan to release the source code of your approach?

Best,
JC

**Comment by mattiasegu** [comment]
Hi @jcsma,

I'm glad you find our work interesting :) I'm planning to polish the code after the CVPR deadline. Targeting early December.

**Comment by heitorrapela** [comment]
@mattiasegu any news about the code?

Best,
Heitor

**Comment by mattiasegu** [comment]
@heitorrapela @jcsma a first version of the code is now available, together with pre-trained checkpoints and usage instructions. Please let me know if you encounter any issue!
